name: Build Example iOS Project

on:
  pull_request:
    branches:
      - master

jobs:
  install:
    name: Install packages
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install

  build-ios-example:
      needs: install
      runs-on: macos-latest
      steps: 
        - uses: actions/checkout@v2
        - name: Install npm dependencies
          run: |
            npm install && cd example && npm install
        - name: Install pod dependencies
          run: |
            cd ios && pod install
        - name: Build app
          run: |       
            xcodebuild xcodebuild -workspace IosContextMenuExample.xcworkspace -configuration Debug -scheme IosContextMenuExample
    
    
