name: Build Example

on:
  pull_request:
  release:
  workflow_dispatch:
    branches:
      - master

jobs:
  build-ios-example:
      runs-on: macos-latest
      steps: 
        - uses: actions/checkout@v2
        - name: Install library npm dependencies
          run: |
            pwd && npm install
        - name: Install example npm dependencies
          run: |
            pwd && cd example && pwd && npm install
        - name: Install example pod dependencies
          run: |
            pwd && cd example/ios && pwd && pod install
        - name: Build app
          run: |       
            pwd && cd example && pwd && npm run ios
    
    
